<?php

namespace dokuwiki\plugin\farmsync\test;

/**
 *
 * @group plugin_farmsync
 * @group plugins
 * @author Michael Große <grosse@cosmocode.de>
 *
 */
class farymsyncutil_farmsync_test extends \DokuWikiTest {

    protected $pluginsEnabled = array('farmsync',);

    public static function setUpBeforeClass() {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        define(DOKU_FARMDIR, '/testfarmdir/' );
    }


    public function test_remoteFilenames() {
        // arrange
        $farm_util = new \dokuwiki\plugin\farmsync\meta\FarmSyncUtil();

        // act
        wikiFN(':start');
        $actual_fn = $farm_util->getRemoteFilename('testanimal', ':start');

        // assert
        $this->assertEquals("/testfarmdir/testanimal/data/pages/start.txt", $actual_fn);
    }

}
